### ISSUE TITLE
Thank you for creating this

### ISSUE THREAD

**Issue by ghost** [boldleadsdevelopment/lockdown#2]
This is an amazing piece of software (ties together so much functionality).

Going to take down this issue later, but just wanted to communicate my thanks to all for posting this on Github. Incredible work and I really appreciate it.

**Comment by iDoMeteor** [comment]
Thank you very much, we're glad that you found it useful!  No need to remove your comment, we appreciate any and all feedback.

As the author of this package, I welcome any additional bug reports or usage issues and am very pleased to know that others are using it as well.
